# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='top_actors',
            field=models.ManyToManyField(blank=True, to='movies.Actors'),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='top_actresses',
            field=models.ManyToManyField(blank=True, to='movies.Actresses'),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='top_directors',
            field=models.ManyToManyField(blank=True, to='movies.Directors'),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='top_movies',
            field=models.ManyToManyField(blank=True, to='movies.Movies'),
        ),
    ]
