# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 07:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='admin_rights',
            field=models.ManyToManyField(blank=True, related_name='admin_rights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groups',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='groups',
            name='image',
            field=models.ImageField(blank=True, default='groups/photos/joker.png', upload_to='groups/photos'),
        ),
    ]
